"""empty message

Revision ID: 9d6cc9f209fe
Revises: d360e9a19376
Create Date: 2023-08-31 17:35:28.248768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d6cc9f209fe'
down_revision = 'd360e9a19376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('user_coin', sa.Integer(), nullable=True),
    sa.Column('user_paper_subject', sa.Integer(), nullable=True),
    sa.Column('required_credit_basic', sa.Integer(), nullable=True),
    sa.Column('complete_credit_basic', sa.Integer(), nullable=True),
    sa.Column('required_credit_major', sa.Integer(), nullable=True),
    sa.Column('complete_credit_major', sa.Integer(), nullable=True),
    sa.Column('required_credit_elec', sa.Integer(), nullable=True),
    sa.Column('complete_credit_elec', sa.Integer(), nullable=True),
    sa.Column('required_credit_general', sa.Integer(), nullable=True),
    sa.Column('complete_credit_general', sa.Integer(), nullable=True),
    sa.Column('required_credit_outer', sa.Integer(), nullable=True),
    sa.Column('complete_credit_outer', sa.Integer(), nullable=True),
    sa.Column('ability_math', sa.Float(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('join_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    op.drop_table('user_profile')
    # ### end Alembic commands ###
