"""empty message

Revision ID: 9f07eea921f1
Revises: 3c82a8ae28ca
Create Date: 2023-09-03 18:32:27.697400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f07eea921f1'
down_revision = '3c82a8ae28ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_teacher',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=30), nullable=True),
    sa.Column('teacher_name', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['course_name'], ['course_info.course_name'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_teacher')
    # ### end Alembic commands ###
