"""empty message

Revision ID: a63c2dbb8666
Revises: cd8478482956
Create Date: 2023-09-14 19:26:23.729104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a63c2dbb8666'
down_revision = 'cd8478482956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_info', schema=None) as batch_op:
        batch_op.alter_column('math',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('coding',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('logic',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('creative',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('solve',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('pass_exam_paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('teacher', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=False))
        batch_op.drop_constraint('pass_exam_paper_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('pass_exam_paper_ibfk_1', type_='foreignkey')
        batch_op.drop_column('course_name')
        batch_op.drop_column('paper_info')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass_exam_paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('paper_info', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('course_name', mysql.VARCHAR(length=30), nullable=True))
        batch_op.create_foreign_key('pass_exam_paper_ibfk_1', 'course_teacher', ['course_id'], ['course_id'])
        batch_op.create_foreign_key('pass_exam_paper_ibfk_2', 'course_info', ['course_name'], ['course_name'])
        batch_op.drop_column('file_data')
        batch_op.drop_column('info')
        batch_op.drop_column('teacher')
        batch_op.drop_column('course')

    with op.batch_alter_table('course_info', schema=None) as batch_op:
        batch_op.alter_column('solve',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('creative',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('logic',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('coding',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('math',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
