"""empty message

Revision ID: af4c429a195c
Revises: 9f07eea921f1
Create Date: 2023-09-03 19:14:25.340815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4c429a195c'
down_revision = '9f07eea921f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_info',
    sa.Column('course_name', sa.String(length=30), nullable=False),
    sa.Column('course_year', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.String(length=30), nullable=False),
    sa.Column('course_credit', sa.Integer(), nullable=False),
    sa.Column('course_intro', sa.Text(), nullable=True),
    sa.Column('math', sa.Integer(), nullable=False),
    sa.Column('coding', sa.Integer(), nullable=False),
    sa.Column('logic', sa.Integer(), nullable=False),
    sa.Column('creative', sa.Integer(), nullable=False),
    sa.Column('solve', sa.Integer(), nullable=False),
    sa.Column('math_txt', sa.Text(), nullable=True),
    sa.Column('coding_txt', sa.Text(), nullable=True),
    sa.Column('logic_txt', sa.Text(), nullable=True),
    sa.Column('creative_txt', sa.Text(), nullable=True),
    sa.Column('solve_txt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('course_name')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('user_coin', sa.Integer(), nullable=True),
    sa.Column('user_paper_subject', sa.Integer(), nullable=True),
    sa.Column('required_credit_basic', sa.Integer(), nullable=True),
    sa.Column('complete_credit_basic', sa.Integer(), nullable=True),
    sa.Column('required_credit_major', sa.Integer(), nullable=True),
    sa.Column('complete_credit_major', sa.Integer(), nullable=True),
    sa.Column('required_credit_elec', sa.Integer(), nullable=True),
    sa.Column('complete_credit_elec', sa.Integer(), nullable=True),
    sa.Column('required_credit_general', sa.Integer(), nullable=True),
    sa.Column('complete_credit_general', sa.Integer(), nullable=True),
    sa.Column('required_credit_outer', sa.Integer(), nullable=True),
    sa.Column('complete_credit_outer', sa.Integer(), nullable=True),
    sa.Column('ability_math', sa.Float(), nullable=True),
    sa.Column('ability_coding', sa.Float(), nullable=True),
    sa.Column('ability_logic', sa.Float(), nullable=True),
    sa.Column('ability_creative', sa.Float(), nullable=True),
    sa.Column('ability_solve', sa.Float(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('course_teacher',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=30), nullable=True),
    sa.Column('teacher_name', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['course_name'], ['course_info.course_name'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('lesson_response',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('command_time', sa.DateTime(), nullable=True),
    sa.Column('liked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_name'], ['course_info.course_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('user_grades',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('course_name', sa.String(length=30), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_name'], ['course_info.course_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_grades')
    op.drop_table('lesson_response')
    op.drop_table('course_teacher')
    op.drop_table('user_profile')
    op.drop_table('course_info')
    # ### end Alembic commands ###
