"""empty message

Revision ID: c65d76a9e552
Revises: 4180b96e3f75
Create Date: 2023-09-03 18:01:51.548733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c65d76a9e552'
down_revision = '4180b96e3f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_info', schema=None) as batch_op:
        batch_op.drop_column('course_id')
        batch_op.drop_column('teacher_name')

    with op.batch_alter_table('lesson_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_name', sa.String(length=30), nullable=True))
        batch_op.drop_constraint('lesson_response_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course_info', ['course_name'], ['course_name'])
        batch_op.drop_column('course_id')

    with op.batch_alter_table('user_grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_name', sa.String(length=30), nullable=True))
        batch_op.drop_constraint('user_grades_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course_info', ['course_name'], ['course_name'])
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_grades_ibfk_1', 'course_info', ['course_id'], ['course_id'])
        batch_op.drop_column('course_name')

    with op.batch_alter_table('lesson_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('lesson_response_ibfk_1', 'course_info', ['course_id'], ['course_id'])
        batch_op.drop_column('course_name')

    with op.batch_alter_table('course_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_name', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
