"""empty message

Revision ID: e9e8381a3e24
Revises: 279e61a61e51
Create Date: 2023-09-08 10:15:17.057375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9e8381a3e24'
down_revision = '279e61a61e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_response', schema=None) as batch_op:
        batch_op.drop_column('liked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
